content:
  - name: entries
    label: Entries
    type: collection
    path: content/entries
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: text
      - name: description
        label: Description
        type: text
      - name: location
        label: Location
        type: string
        options:
          maxlength: 20
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: body
        label: Content
        type: text